using Xunit;

namespace agency_transfercenter.EntityFrameworkCore;

[CollectionDefinition(agency_transfercenterTestConsts.CollectionDefinitionName)]
public class agency_transfercenterEntityFrameworkCoreCollection : ICollectionFixture<agency_transfercenterEntityFrameworkCoreFixture>
{

}
