using agency_transfercenter.EntityFrameworkCore;
using Xunit;

namespace agency_transfercenter.EntityFrameworkCore;

public class agency_transfercenterEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<agency_transfercenterEntityFrameworkCoreFixture>
{

}
